export const UI_ADD_NOTE_ITEM = 'UI_ADD_NOTE_ITEM'
export const UI_REMOVE_NOTE_ITEM = 'UI_REMOVE_NOTE_ITEM'

export const NOTE_GROUPS_LOADED = 'NOTE_GROUPS_LOADED'
export const ADD_NOTE_GROUP = 'ADD_NOTE_GROUP'
export const REMOVE_NOTE_GROUP = 'REMOVE_NOTE_GROUP'

export const NOTE_ITEMS_LOADED = 'NOTE_ITEMS_LOADED'
export const ADD_NOTE_ITEM = 'ADD_NOTE_ITEM'
export const REMOVE_NOTE_ITEM = 'REMOVE_NOTE_ITEM'

export const TOPICS_LOADED = 'TOPICS_LOADED'
export const SELECT_TOPIC = 'SELECT_TOPIC'
